const products=[
{id:"ares",name:"Ares",type:"rank",kicker:"Привилегия I",badge:"Старт",price:99,oldPrice:129,image:"ares.webp",accent:"#ffb84d",description:"Базовый набор команд и заметный префикс в чате."},
{id:"musketeer",name:"Musketeer",type:"rank",kicker:"Привилегия II",badge:"Выгодно",price:199,oldPrice:249,image:"musketeer.webp",accent:"#62cfff",description:"Больше возможностей, китов и слотов на аукционе."},
{id:"spartan",name:"Spartan",type:"rank",kicker:"Привилегия III",badge:"Популярно",price:349,oldPrice:439,image:"spartan.webp",accent:"#ff746f",description:"Боевые бонусы и расширенный набор команд игрока."},
{id:"apex",name:"Apex",type:"rank",kicker:"Привилегия IV",badge:"Премиум",price:599,oldPrice:749,image:"apex.webp",accent:"#ae70ff",description:"Премиум-возможности для настоящих лидеров."},
{id:"phoenix",name:"Phoenix",type:"rank",kicker:"Привилегия V",badge:"Топ ранг",price:899,oldPrice:1129,image:"phoenix.webp",accent:"#ff812a",description:"Максимальный ранг сезона и уникальный статус."},
{id:"donate-case",name:"Донат-кейс",type:"case",kicker:"Случайная награда",badge:"Кейс",price:39,image:"donate-case.webp",accent:"#d06cff",description:"Испытай удачу и получи одну из привилегий."},
{id:"titles-3",name:"3 кейса с титулами",type:"case",kicker:"Набор титулов",badge:"3 кейса",price:15,image:"titles-3.webp",accent:"#6decaa",description:"Три шанса открыть новый титул для профиля."},
{id:"titles-10",name:"10 кейсов с титулами",type:"case",kicker:"Набор титулов",badge:"10 кейсов",price:35,image:"titles-10.webp",accent:"#ffcb5e",description:"Выгодный набор для пополнения коллекции титулов."},
{id:"titles-25",name:"25 кейсов с титулами",type:"case",kicker:"Большой набор",badge:"25 кейсов",price:85,image:"unmute.webp",accent:"#5aaeff",description:"Максимум открытий по самой выгодной цене."},
{id:"unban",name:"Разбан",type:"service",kicker:"Услуга",badge:"Возврат в игру",price:110,image:"unban.webp",accent:"#ff5e53",description:"Снятие активной блокировки игрового аккаунта."},
{id:"unmute",name:"Размут",type:"service",kicker:"Услуга",badge:"Чат",price:45,image:"titles-25.webp",accent:"#6b9dff",description:"Снятие активной блокировки игрового чата."}
];
const money=value=>`${new Intl.NumberFormat("ru-RU").format(value)} ₽`;
const productGrid=document.querySelector("[data-products]"),cartDrawer=document.querySelector("[data-cart-drawer]"),backdrop=document.querySelector("[data-backdrop]"),cartItems=document.querySelector("[data-cart-items]"),emptyState=document.querySelector("[data-cart-empty]"),summary=document.querySelector("[data-cart-summary]"),totalNode=document.querySelector("[data-cart-total]"),countNodes=document.querySelectorAll("[data-cart-count]"),toast=document.querySelector("[data-toast]");
let cart=[],toastTimer,backdropTimer,lastFocused;try{cart=JSON.parse(localStorage.getItem("sunpvp-cart"))||[]}catch{cart=[]}
function renderProducts(filter="all"){productGrid.innerHTML=products.map((p,index)=>`<article class="product-card" data-type="${p.type}" style="--accent:${p.accent};animation-delay:${Math.min(index*35,250)}ms" ${filter!=="all"&&filter!==p.type?"hidden":""}><div class="card-media"><img src="${p.image}" alt="${p.name}" loading="${index<3?"eager":"lazy"}" width="960" height="640"><span class="card-badge">${p.badge}</span></div><div class="card-body"><p class="card-kicker">${p.kicker}</p><h3>${p.name}</h3><p class="card-description">${p.description}</p><div class="card-buy-row"><div class="price"><strong>${money(p.price)}</strong>${p.oldPrice?`<span class="old-price">${money(p.oldPrice)}</span>`:""}</div><button class="add-button" type="button" data-add="${p.id}" aria-label="Добавить ${p.name} в корзину"><span>+</span><span>Добавить</span></button></div></div></article>`).join("")}
function saveCart(){localStorage.setItem("sunpvp-cart",JSON.stringify(cart));renderCart()}
function renderCart(){countNodes.forEach(n=>n.textContent=cart.length);const entries=cart.map(id=>products.find(p=>p.id===id)).filter(Boolean);cartItems.innerHTML=entries.map((p,index)=>`<div class="cart-item"><img src="${p.image}" alt="" width="66" height="58"><div class="cart-item-copy"><b>${p.name}</b><small>${money(p.price)}</small></div><button class="remove-item" type="button" data-remove-index="${index}" aria-label="Удалить ${p.name}">×</button></div>`).join("");const hasItems=entries.length>0;emptyState.hidden=hasItems;summary.hidden=!hasItems;totalNode.textContent=money(entries.reduce((total,p)=>total+p.price,0))}
function addToCart(id){const p=products.find(item=>item.id===id);if(!p)return;cart.push(id);saveCart();showToast(`${p.name} добавлен в корзину`)}
function openCart(){clearTimeout(backdropTimer);lastFocused=document.activeElement;backdrop.hidden=false;cartDrawer.inert=false;document.querySelector("[data-open-cart]").setAttribute("aria-expanded","true");requestAnimationFrame(()=>backdrop.classList.add("show"));cartDrawer.classList.add("open");cartDrawer.setAttribute("aria-hidden","false");document.body.classList.add("drawer-open");cartDrawer.querySelector("[data-close-cart]").focus()}
function closeCart(){clearTimeout(backdropTimer);backdrop.classList.remove("show");cartDrawer.classList.remove("open");cartDrawer.setAttribute("aria-hidden","true");document.querySelector("[data-open-cart]").setAttribute("aria-expanded","false");document.body.classList.remove("drawer-open");backdropTimer=setTimeout(()=>{backdrop.hidden=true;cartDrawer.inert=true},250);if(lastFocused?.focus)lastFocused.focus()}
function showToast(message){toast.textContent=message;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),2600)}
document.addEventListener("click",event=>{const addButton=event.target.closest("[data-add]"),removeButton=event.target.closest("[data-remove-index]"),scrollButton=event.target.closest("[data-scroll-shop]");if(addButton)addToCart(addButton.dataset.add);if(removeButton){cart.splice(Number(removeButton.dataset.removeIndex),1);saveCart()}if(event.target.closest("[data-open-cart]"))openCart();if(event.target.closest("[data-close-cart]")||event.target===backdrop){closeCart();if(scrollButton)setTimeout(()=>document.querySelector("#shop").scrollIntoView({behavior:"smooth",block:"start"}),280)}const filterButton=event.target.closest("[data-filter]");if(filterButton){document.querySelectorAll("[data-filter]").forEach(button=>{const active=button===filterButton;button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active))});renderProducts(filterButton.dataset.filter)}});
document.addEventListener("keydown",event=>{if(!cartDrawer.classList.contains("open"))return;if(event.key==="Escape"){closeCart();return}if(event.key==="Tab"){const focusable=[...cartDrawer.querySelectorAll("button:not([disabled]),input:not([disabled]),a[href]")].filter(element=>!element.closest("[hidden]"));if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}});
document.querySelector("[data-checkout]").addEventListener("click",()=>{const nickname=document.querySelector("#nickname");if(!/^[A-Za-z0-9_]{3,16}$/.test(nickname.value.trim())){nickname.focus();showToast("Укажи корректный ник: 3–16 символов");return}showToast("Заказ собран. Оплату подключим следующим этапом")});
function registerWebMcpTools(){const context=document.modelContext;if(!context?.registerTool)return;const register=tool=>{try{void Promise.resolve(context.registerTool(tool)).catch(()=>undefined)}catch{}};register({name:"browse_sunpvp_catalog",title:"Каталог SunPvP",description:"Показать товары магазина SunPvP с ценами и категориями.",inputSchema:{type:"object",properties:{category:{type:"string",enum:["all","rank","case","service"]}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){const category=input?.category||"all";return products.filter(p=>category==="all"||p.type===category).map(({id,name,type,price})=>({id,name,type,price}))}});register({name:"add_sunpvp_products_to_cart",title:"Добавить товары в корзину",description:"Добавить один или несколько товаров SunPvP в текущую корзину.",inputSchema:{type:"object",properties:{productIds:{type:"array",minItems:1,items:{type:"string"}}},required:["productIds"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!Array.isArray(input?.productIds)||!input.productIds.length)throw new Error("Укажите товары");input.productIds.forEach(id=>{if(!products.some(p=>p.id===id))throw new Error(`Товар не найден: ${id}`)});cart.push(...input.productIds);saveCart();return{itemCount:cart.length,total:cart.reduce((sum,id)=>sum+(products.find(p=>p.id===id)?.price||0),0)}}})}
renderProducts();renderCart();registerWebMcpTools();
